import { useForm, usePage } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';
import Pagination from '../../components/Pagination';
import { dateToday, fullName, time12 } from '../../lib/format';

export default function AttendanceIndex({ employees, logs }) {
    const { auth } = usePage().props;
    const canManage = auth.user.role !== 'faculty';
    const firstEmployee = employees[0]?.id || '';
    const tap = useForm({ identifier: '', method: 'rfid' });
    const manual = useForm({ employee_id: firstEmployee, attendance_date: dateToday(), time_in: '', time_out: '', remarks: '' });
    const testLogs = useForm({ employee_id: firstEmployee, start_date: dateToday(), end_date: dateToday() });
    return <AppLayout title="Attendance" subtitle="Record attendance through RFID, fingerprint code, or manual entry.">
        {canManage && <><section className="content-grid">
            <form className="panel compact-form" onSubmit={(e) => { e.preventDefault(); tap.post('/attendance/tap'); }}><h2>RFID / Fingerprint Tap</h2><label>Identifier<input placeholder="Scan RFID UID or fingerprint code" value={tap.data.identifier} onChange={(e) => tap.setData('identifier', e.target.value)} required autoFocus /></label><label>Method<select value={tap.data.method} onChange={(e) => tap.setData('method', e.target.value)}><option value="rfid">RFID</option><option value="fingerprint">Fingerprint</option></select></label><button type="submit" disabled={tap.processing}>Record Tap</button></form>
            <form className="panel compact-form" onSubmit={(e) => { e.preventDefault(); manual.post('/attendance/manual'); }}><h2>Manual Attendance</h2><label>Faculty<select value={manual.data.employee_id} onChange={(e) => manual.setData('employee_id', e.target.value)} required>{employees.map((employee) => <option key={employee.id} value={employee.id}>{fullName(employee)}</option>)}</select></label><label>Date<input type="date" value={manual.data.attendance_date} onChange={(e) => manual.setData('attendance_date', e.target.value)} required /></label><label>Time In<input type="time" value={manual.data.time_in} onChange={(e) => manual.setData('time_in', e.target.value)} /></label><label>Time Out<input type="time" value={manual.data.time_out} onChange={(e) => manual.setData('time_out', e.target.value)} /></label><label>Remarks<input value={manual.data.remarks} onChange={(e) => manual.setData('remarks', e.target.value)} /></label><button type="submit" disabled={manual.processing}>Save Manual Log</button></form>
        </section>
        <section className="panel test-attendance-panel"><div><h2>Generate Schedule-Based Test Attendance</h2><p>Creates complete attendance only on the selected faculty member's scheduled days. Existing attendance logs are preserved.</p></div><form className="test-attendance-form" onSubmit={(e) => { e.preventDefault(); testLogs.post('/attendance/generate-test'); }}><label>Faculty<select value={testLogs.data.employee_id} onChange={(e) => testLogs.setData('employee_id', e.target.value)}>{employees.map((employee) => <option key={employee.id} value={employee.id}>{fullName(employee)}</option>)}</select></label><label>Start Date<input type="date" value={testLogs.data.start_date} onChange={(e) => testLogs.setData('start_date', e.target.value)} /></label><label>End Date<input type="date" value={testLogs.data.end_date} onChange={(e) => testLogs.setData('end_date', e.target.value)} /></label><button type="submit" disabled={testLogs.processing}>Generate Test Logs</button></form></section></>}
        <div className="panel"><div className="panel-heading"><h2>{canManage ? 'Attendance Logs' : 'My Attendance Logs'}</h2></div><div className="table-wrap"><table><thead><tr><th>Faculty</th><th>Date</th><th>Time In</th><th>Time Out</th><th>Method</th><th>Hours</th><th>Late</th><th>Undertime</th><th>Status</th></tr></thead><tbody>{logs.data.length ? logs.data.map((log) => <tr key={log.id}><td>{fullName(log.employee)}</td><td>{log.attendance_date}</td><td>{time12(log.time_in)}</td><td>{time12(log.time_out)}</td><td>{log.method_in || '-'} / {log.method_out || '-'}</td><td>{log.total_hours}</td><td>{log.late_minutes} min</td><td>{log.undertime_minutes} min</td><td><span className="badge">{log.status}</span></td></tr>) : <tr><td colSpan="9">No attendance logs yet.</td></tr>}</tbody></table></div><Pagination links={logs.links} /></div>
    </AppLayout>;
}
